### ISSUE TITLE
springboot启动时报错：org.springframework.beans.FatalBeanException: There may be an error in the transaction configuration.

### ISSUE THREAD

**Issue by Klose2013** [liuyangming/ByteTCC#110]
````
Caused by: org.springframework.beans.FatalBeanException: There may be an error in the transaction configuration.
	at org.bytesoft.bytetcc.supports.spring.TransactionAdviceOrderStraightener.switchAdvisorOrderIfNecessary(TransactionAdviceOrderStraightener.java:79) ~[bytetcc-supports-0.5.7.jar:?]
	at org.bytesoft.bytetcc.supports.spring.TransactionAdviceOrderStraightener.postProcessAfterInitialization(TransactionAdviceOrderStraightener.java:33) ~[bytetcc-supports-0.5.7.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:429) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
````

项目中取消自动加载数据源

**Comment by Klose2013** [comment]
已启动，没有加事务注解
