### ISSUE TITLE
去除eureka使用nacos一直报错

### ISSUE THREAD

**Issue by checkHup** [liuyangming/ByteTCC#152]
使用0.5.12版本，依赖中去除eureka，但是一直报错：Caused by: java.lang.NoClassDefFoundError: com/netflix/discovery/AbstractDiscoveryClientOptionalArgs
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_141]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_141]
	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_141]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 33 common frames omitted

想问一下，现在可以支持nacos嘛

**Comment by FansinZhao** [comment]
我已收到您的邮件！谢谢

**Comment by checkHup** [comment]
> 我已收到您的邮件！谢谢

打扰了，有好几处引用了eureka，需要都去除才可以
