### ISSUE TITLE
dubbo中使用时  消费者报错

### ISSUE THREAD

**Issue by ty1972873004** [liuyangming/ByteTCC#21]
java.lang.IllegalStateException: Class com.javaxxw.manager.service.impl.TransferServiceImpl does not implement interface org.bytesoft.bytetcc.supports.spring.aware.CompensableBeanNameAware, and there are multiple bean definitions!
	at org.bytesoft.bytetcc.supports.spring.CompensableMethodInterceptor.invoke(CompensableMethodInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at com.javaxxw.manager.service.impl.TransferServiceImpl$$EnhancerBySpringCGLIB$$c5a4e117.transfer()
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by liuyangming** [comment]
类com.javaxxw.manager.service.impl.TransferServiceImpl要么实现接口CompensableBeanNameAware，要么只定义一个bean实例。不实现CompensableBeanNameAware接口且存在多个bean实例时，会导致ByteTCC获取不了该服务的beanId。
