### ISSUE TITLE
请问com.caucho.hessian.io.HessianProtocolException: unknown code for readObject at end of file怎么解决

### ISSUE THREAD

**Issue by pengyanping** [liuyangming/ByteTCC#24]
com.caucho.hessian.io.HessianProtocolException: unknown code for readObject at end of file
	at com.caucho.hessian.io.HessianInput.error(HessianInput.java:1697) ~[hessian-4.0.38.jar:na]
	at com.caucho.hessian.io.HessianInput.readObject(HessianInput.java:1177) ~[hessian-4.0.38.jar:na]
	at org.bytesoft.common.utils.CommonUtils.deserializeObject(CommonUtils.java:62) ~[bytejta-core-0.4.0-alpha4.jar:na]
	at org.bytesoft.bytetcc.supports.springcloud.web.CompensableRequestInterceptor.invokeAfterRecvResponse(CompensableRequestInterceptor.java:193) ~[bytetcc-supports-springcloud-0.4.0-beta2.jar:na]
	at org.bytesoft.bytetcc.supports.springcloud.web.CompensableRequestInterceptor.intercept(CompensableRequestInterceptor.java:150) ~[bytetcc-supports-springcloud-0.4.0-beta2.jar:na]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:86) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:70) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:652) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:407) ~[spring-web-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at com.bytesvc.consumer.service.impl.TransferService.transfer(TransferService.java:40) ~[classes/:na]
	at com.bytesvc.consumer.controller.TransferController.transfer(TransferController.java:38) ~[classes/:na]
	at com.bytesvc.consumer.controller.TransferController$$FastClassBySpringCGLIB$$d59c2c04.invoke(<generated>) ~[classes/:na]

**Comment by liuyangming** [comment]
可能是hessian版本不兼容。。。什么情况下会出现这个问题？
