### ISSUE TITLE
升级到 0.4.11 NoSuchMethodError

### ISSUE THREAD

**Issue by wujun8** [liuyangming/ByteTCC#51]
使用 ByteTCC-sample 最新代码，出现下面的异常
```
2018-04-24 10:39:15,905 INFO  [main] org.springframework.context.support.ClassPathXmlApplicationContext - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@39fe9ce1: startup date [Tue Apr 24 10:39:15 CST 2018]; root of context hierarchy
2018-04-24 10:39:15,977 INFO  [main] org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [application.xml]
2018-04-24 10:39:16,104 INFO  [main] org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [bytetcc-supports-dubbo.xml]
2018-04-24 10:39:16,140 INFO  [main] org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [bytetcc-disable-tx-advice.xml]
2018-04-24 10:39:16,164 INFO  [main] org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [bytetcc-supports-dubbo-core.xml]
2018-04-24 10:39:16,184 INFO  [main] org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [bytetcc-supports-jta.xml]
2018-04-24 10:39:16,202 INFO  [main] org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [bytetcc-supports-tcc.xml]
2018-04-24 10:39:16,229 INFO  [main] org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [bytetcc-supports-task.xml]
2018-04-24 10:39:16,306 INFO  [main] org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [dubbo-consumer.xml]
2018-04-24 10:39:16,829 WARN  [main] org.bytesoft.bytetcc.supports.dubbo.validator.ReferenceConfigValidator - The remote call method(public abstract void com.bytesvc.service.IAccountService.increaseAmount(java.lang.String,double) throws com.bytesvc.ServiceException) should be declared to throw a remote exception: org.bytesoft.compensable.RemotingException!
2018-04-24 10:39:16,829 WARN  [main] org.bytesoft.bytetcc.supports.dubbo.validator.ReferenceConfigValidator - The remote call method(public abstract void com.bytesvc.service.IAccountService.decreaseAmount(java.lang.String,double) throws com.bytesvc.ServiceException) should be declared to throw a remote exception: org.bytesoft.compensable.RemotingException!
2018-04-24 10:39:16,835 INFO  [main] org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2018-04-24 10:39:16,897 INFO  [main] org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.aop.support.DefaultBeanFactoryPointcutAdvisor#0' of type [org.springframework.aop.support.DefaultBeanFactoryPointcutAdvisor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-04-24 10:39:17,715 INFO  [ZkClient-EventThread-18-localhost:2181] org.I0Itec.zkclient.ZkEventThread - Starting ZkClient event thread.
2018-04-24 10:39:22,325 INFO  [main-EventThread] org.I0Itec.zkclient.ZkClient - zookeeper state changed (SyncConnected)
2018-04-24 10:39:22,624 INFO  [main] org.springframework.transaction.jta.JtaTransactionManager - Using JTA UserTransaction: org.bytesoft.bytetcc.UserCompensableImpl@128bc54a
2018-04-24 10:39:22,625 INFO  [main] org.springframework.transaction.jta.JtaTransactionManager - Using JTA TransactionManager: org.bytesoft.bytetcc.TransactionManagerImpl@488d3603
2018-04-24 10:39:27,071 INFO  [main] org.bytesoft.bytetcc.CompensableTransactionImpl - 0a002700000400000162f5851c0d000154a084d1| register compensable service: 0a002700000400000162f5851c0d000154a084d1.
2018-04-24 10:39:27,173 INFO  [main] org.bytesoft.bytetcc.CompensableManagerImpl - 0a002700000400000162f5851c0d000154a084d1| compensable transaction begin!
2018-04-24 10:39:27,241 INFO  [main] org.bytesoft.bytetcc.CompensableTransactionImpl - 0a002700000400000162f5851c0d000154a084d1| enlist remote resource: 192.168.99.1:sample-provider:20882.
2018-04-24 10:39:27,279 INFO  [main] org.bytesoft.bytejta.TransactionImpl - [0a002700000400000162f5851c0d000154a084d1] rollback-transaction start
2018-04-24 10:39:27,280 INFO  [main] org.bytesoft.bytejta.TransactionImpl - [0a002700000400000162f5851c0d000154a084d1] rollback-transaction complete successfully
2018-04-24 10:39:27,280 INFO  [main] org.bytesoft.bytetcc.CompensableTransactionImpl - 0a002700000400000162f5851c0d000154a084d1| The operation in try phase is rolled back, so the cancel operation is ignored, compensable service: 0a002700000400000162f5851c0d000154a084d1.
Exception in thread "main" java.lang.NoSuchMethodError: org.bytesoft.compensable.CompensableInvocation.isEnlisted()Z
	at org.bytesoft.bytetcc.supports.spring.CompensableMethodInterceptor.afterBegin(CompensableMethodInterceptor.java:63)
	at org.bytesoft.bytetcc.CompensableManagerImpl.invokeBegin(CompensableManagerImpl.java:167)
	at org.bytesoft.bytetcc.CompensableManagerImpl.begin(CompensableManagerImpl.java:146)
	at org.bytesoft.bytetcc.TransactionManagerImpl.begin(TransactionManagerImpl.java:54)
	at org.bytesoft.bytetcc.UserCompensableImpl.begin(UserCompensableImpl.java:87)
	at org.springframework.transaction.jta.JtaTransactionManager.doJtaBegin(JtaTransactionManager.java:875)
	at org.springframework.transaction.jta.JtaTransactionManager.doBegin(JtaTransactionManager.java:832)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:420)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:257)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.bytesoft.bytetcc.supports.spring.CompensableMethodInterceptor.execute(CompensableMethodInterceptor.java:193)
	at org.bytesoft.bytetcc.supports.spring.CompensableMethodInterceptor.invoke(CompensableMethodInterceptor.java:103)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:644)
	at com.bytesvc.service.impl.AccountServiceImpl$$EnhancerBySpringCGLIB$$3f3902a.decreaseAmount(<generated>)
	at com.alibaba.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	at org.bytesoft.bytetcc.supports.dubbo.spi.CompensableServiceFilter.wrapResultForProvider(CompensableServiceFilter.java:285)
	at org.bytesoft.bytetcc.supports.dubbo.spi.CompensableServiceFilter.providerInvokeForSVC(CompensableServiceFilter.java:251)
	at org.bytesoft.bytetcc.supports.dubbo.spi.CompensableServiceFilter.providerInvoke(CompensableServiceFilter.java:88)
	at org.bytesoft.bytetcc.supports.dubbo.spi.CompensableServiceFilter.invoke(CompensableServiceFilter.java:71)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:112)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2018-04-24 10:39:27,283 INFO  [main] org.bytesoft.bytetcc.CompensableTransactionImpl - 0a002700000400000162f5851c0d000154a084d1| cancel remote branch: 192.168.99.1:sample-provider:20882
2018-04-24 10:39:27,283 INFO  [main] org.bytesoft.bytetcc.CompensableTransactionImpl - 0a002700000400000162f5851c0d000154a084d1| compensable transaction rolled back!
2018-04-24 10:39:27,283 INFO  [main] org.bytesoft.bytetcc.CompensableTransactionImpl - 0a002700000400000162f5851c0d000154a084d1| forget transaction.
```

**Comment by liuyangming** [comment]
CompensableInvocation.isEnlisted()方法是在0.4.11版本中添加的，出现该异常可能是引入的bytetcc-common和bytetcc-supports包版本不一致导致。

**Comment by wujun8** [comment]
我的错误是由于另外有独立打开 sample-provider module ，其依赖的 sample-api 需要 install 到 Maven local Repository，更新后未重新 install ，bytetcc 版本不一致
