### ISSUE TITLE
TCC confirm 调用错位

### ISSUE THREAD

**Issue by wujun8** [liuyangming/ByteTCC#52]
调试过程发现一个问题，provider 端 confirm 存在 bug，然后重启，大概率出现事务恢复初始化失败，然后 confirm 重试的时候就不对了, 这个 https://github.com/wujun8/ByteTCC-sample/tree/confirm-compensableContext-bug 可以重现，应该是前面提到的 Map 序列化问题，但是不至于影响到调用链吧
```
2018-04-25 11:30:47,818 INFO  [ZkClient-EventThread-18-localhost:2181] org.I0Itec.zkclient.ZkEventThread - Starting ZkClient event thread.
2018-04-25 11:30:47,823 ERROR [pool-1-thread-1] org.bytesoft.bytetcc.logging.deserializer.TransactionArchiveDeserializer - Error occurred while deserializing object: [1, 1, 0, 106, 97, 118, 97, 46, 117, 116, 105, 108, 46, 72, 97, 115, 104, 77, 97, -16, 1, 1, 3, 1, 100, 97, 116, 97, 45, 97, 102, 116, 101, 114, 45, 114, 101, 115, 116, 97, 114, -12, 3, 1, 49, 49, 49, 49, 50, 50, 50, -78]
com.caucho.hessian.io.HessianProtocolException: unknown code for readObject at 0x1 ()
	at com.caucho.hessian.io.HessianInput.error(HessianInput.java:1697)
	at com.caucho.hessian.io.HessianInput.readObject(HessianInput.java:1177)
	at org.bytesoft.common.utils.SerializeUtils.hessianDeserialize(SerializeUtils.java:165)
	at org.bytesoft.common.utils.CommonUtils.deserializeObject(CommonUtils.java:75)
	at org.bytesoft.bytetcc.logging.deserializer.TransactionArchiveDeserializer.deserialize(TransactionArchiveDeserializer.java:221)
	at org.bytesoft.bytetcc.logging.ArchiveDeserializerImpl.deserialize(ArchiveDeserializerImpl.java:72)
	at org.bytesoft.bytetcc.logging.SampleCompensableLogger$2.execOperation(SampleCompensableLogger.java:161)
	at org.bytesoft.bytetcc.logging.SampleCompensableLogger$2.recvOperation(SampleCompensableLogger.java:152)
	at org.bytesoft.bytejta.logging.store.VirtualLoggingSystemImpl.traversal(VirtualLoggingSystemImpl.java:181)
	at org.bytesoft.bytetcc.logging.SampleCompensableLogger.recover(SampleCompensableLogger.java:148)
	at org.bytesoft.bytetcc.TransactionRecoveryImpl.fireCompensableStartRecovery(TransactionRecoveryImpl.java:92)
	at org.bytesoft.bytetcc.TransactionRecoveryImpl.startRecovery(TransactionRecoveryImpl.java:80)
	at org.bytesoft.bytetcc.work.CompensableWork.initializeIfNecessary(CompensableWork.java:43)
	at org.bytesoft.bytetcc.work.CompensableWork.run(CompensableWork.java:55)
	at org.bytesoft.transaction.work.SimpleWork.run(SimpleWork.java:30)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:262)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2018-04-25 11:30:47,826 ERROR [pool-1-thread-1] org.bytesoft.bytetcc.logging.deserializer.TransactionArchiveDeserializer - Error occurred while deserializing object: [1, 1, 0, 106, 97, 118, 97, 46, 117, 116, 105, 108, 46, 72, 97, 115, 104, 77, 97, -16, 1, 1, 3, 1, 100, 97, 116, 97, 45, 97, 102, 116, 101, 114, 45, 114, 101, 115, 116, 97, 114, -12, 3, 1, 49, 49, 49, 49, 50, 50, 50, -78]
com.caucho.hessian.io.HessianProtocolException: unknown code for readObject at 0x1 ()
	at com.caucho.hessian.io.HessianInput.error(HessianInput.java:1697)
	at com.caucho.hessian.io.HessianInput.readObject(HessianInput.java:1177)
	at org.bytesoft.common.utils.SerializeUtils.hessianDeserialize(SerializeUtils.java:165)
	at org.bytesoft.common.utils.CommonUtils.deserializeObject(CommonUtils.java:75)
	at org.bytesoft.bytetcc.logging.deserializer.TransactionArchiveDeserializer.deserialize(TransactionArchiveDeserializer.java:221)
	at org.bytesoft.bytetcc.logging.ArchiveDeserializerImpl.deserialize(ArchiveDeserializerImpl.java:72)
	at org.bytesoft.bytetcc.logging.SampleCompensableLogger$2.execOperation(SampleCompensableLogger.java:161)
	at org.bytesoft.bytetcc.logging.SampleCompensableLogger$2.recvOperation(SampleCompensableLogger.java:152)
	at org.bytesoft.bytejta.logging.store.VirtualLoggingSystemImpl.traversal(VirtualLoggingSystemImpl.java:181)
	at org.bytesoft.bytetcc.logging.SampleCompensableLogger.recover(SampleCompensableLogger.java:148)
	at org.bytesoft.bytetcc.TransactionRecoveryImpl.fireCompensableStartRecovery(TransactionRecoveryImpl.java:92)
	at org.bytesoft.bytetcc.TransactionRecoveryImpl.startRecovery(TransactionRecoveryImpl.java:80)
	at org.bytesoft.bytetcc.work.CompensableWork.initializeIfNecessary(CompensableWork.java:43)
	at org.bytesoft.bytetcc.work.CompensableWork.run(CompensableWork.java:55)
	at org.bytesoft.transaction.work.SimpleWork.run(SimpleWork.java:30)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:262)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2018-04-25 11:30:47,828 ERROR [pool-1-thread-1] org.bytesoft.bytetcc.logging.deserializer.TransactionArchiveDeserializer - Error occurred while deserializing object: [1, 1, 0, 106, 97, 118, 97, 46, 117, 116, 105, 108, 46, 72, 97, 115, 104, 77, 97, -16, 1, 1, 3, 1, 100, 97, 116, 97, 45, 97, 102, 116, 101, 114, 45, 114, 101, 115, 116, 97, 114, -12, 3, 1, 49, 49, 49, 49, 50, 50, 50, -78]
com.caucho.hessian.io.HessianProtocolException: unknown code for readObject at 0x1 ()
	at com.caucho.hessian.io.HessianInput.error(HessianInput.java:1697)
	at com.caucho.hessian.io.HessianInput.readObject(HessianInput.java:1177)
	at org.bytesoft.common.utils.SerializeUtils.hessianDeserialize(SerializeUtils.java:165)
	at org.bytesoft.common.utils.CommonUtils.deserializeObject(CommonUtils.java:75)
	at org.bytesoft.bytetcc.logging.deserializer.TransactionArchiveDeserializer.deserialize(TransactionArchiveDeserializer.java:221)
	at org.bytesoft.bytetcc.logging.ArchiveDeserializerImpl.deserialize(ArchiveDeserializerImpl.java:72)
	at org.bytesoft.bytetcc.logging.SampleCompensableLogger$2.execOperation(SampleCompensableLogger.java:161)
	at org.bytesoft.bytetcc.logging.SampleCompensableLogger$2.recvOperation(SampleCompensableLogger.java:152)
	at org.bytesoft.bytejta.logging.store.VirtualLoggingSystemImpl.traversal(VirtualLoggingSystemImpl.java:181)
	at org.bytesoft.bytetcc.logging.SampleCompensableLogger.recover(SampleCompensableLogger.java:148)
	at org.bytesoft.bytetcc.TransactionRecoveryImpl.fireCompensableStartRecovery(TransactionRecoveryImpl.java:92)
	at org.bytesoft.bytetcc.TransactionRecoveryImpl.startRecovery(TransactionRecoveryImpl.java:80)
	at org.bytesoft.bytetcc.work.CompensableWork.initializeIfNecessary(CompensableWork.java:43)
	at org.bytesoft.bytetcc.work.CompensableWork.run(CompensableWork.java:55)
	at org.bytesoft.transaction.work.SimpleWork.run(SimpleWork.java:30)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:262)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2018-04-25 11:30:47,829 ERROR [pool-1-thread-1] org.bytesoft.bytetcc.logging.deserializer.TransactionArchiveDeserializer - Error occurred while deserializing object: [1, 1, 0, 106, 97, 118, 97, 46, 117, 116, 105, 108, 46, 72, 97, 115, 104, 77, 97, -16, 1, 1, 3, 1, 100, 97, 116, 97, 45, 97, 102, 116, 101, 114, 45, 114, 101, 115, 116, 97, 114, -12, 3, 1, 49, 49, 49, 49, 50, 50, 50, -78]
com.caucho.hessian.io.HessianProtocolException: unknown code for readObject at 0x1 ()
	at com.caucho.hessian.io.HessianInput.error(HessianInput.java:1697)
	at com.caucho.hessian.io.HessianInput.readObject(HessianInput.java:1177)
	at org.bytesoft.common.utils.SerializeUtils.hessianDeserialize(SerializeUtils.java:165)
	at org.bytesoft.common.utils.CommonUtils.deserializeObject(CommonUtils.java:75)
	at org.bytesoft.bytetcc.logging.deserializer.TransactionArchiveDeserializer.deserialize(TransactionArchiveDeserializer.java:221)
	at org.bytesoft.bytetcc.logging.ArchiveDeserializerImpl.deserialize(ArchiveDeserializerImpl.java:72)
	at org.bytesoft.bytetcc.logging.SampleCompensableLogger$2.execOperation(SampleCompensableLogger.java:161)
	at org.bytesoft.bytetcc.logging.SampleCompensableLogger$2.recvOperation(SampleCompensableLogger.java:152)
	at org.bytesoft.bytejta.logging.store.VirtualLoggingSystemImpl.traversal(VirtualLoggingSystemImpl.java:181)
	at org.bytesoft.bytetcc.logging.SampleCompensableLogger.recover(SampleCompensableLogger.java:148)
	at org.bytesoft.bytetcc.TransactionRecoveryImpl.fireCompensableStartRecovery(TransactionRecoveryImpl.java:92)
	at org.bytesoft.bytetcc.TransactionRecoveryImpl.startRecovery(TransactionRecoveryImpl.java:80)
	at org.bytesoft.bytetcc.work.CompensableWork.initializeIfNecessary(CompensableWork.java:43)
	at org.bytesoft.bytetcc.work.CompensableWork.run(CompensableWork.java:55)
	at org.bytesoft.transaction.work.SimpleWork.run(SimpleWork.java:30)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:262)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2018-04-25 11:30:52,391 INFO  [main-EventThread] org.I0Itec.zkclient.ZkClient - zookeeper state changed (SyncConnected)
```

转账，应该是 provider decreaseAmount，结果却调用了 increaseAmount
```
2018-04-25 11:30:53,804 INFO  [main] org.springframework.transaction.jta.JtaTransactionManager - Using JTA UserTransaction: org.bytesoft.bytetcc.UserCompensableImpl@5491669a
2018-04-25 11:30:53,804 INFO  [main] org.springframework.transaction.jta.JtaTransactionManager - Using JTA TransactionManager: org.bytesoft.bytetcc.TransactionManagerImpl@22947acd
sample-provider started!
decreaseAmount
2018-04-25 11:32:03,804 INFO  [main-EventThread] org.I0Itec.zkclient.ZkClient - zookeeper state changed (Disconnected)
2018-04-25 11:33:07,496 INFO  [DubboServerHandler-192.168.99.1:20882-thread-3] org.bytesoft.bytejta.TransactionImpl - [0a002700000400000162fadb19ba00014f694991] enlist: xares= xa-res-archive[descriptor: local-xa-resource[dataSource]], branch= 0a002700000400000162fadca7270002f769c444, flags: 0
done increase: acct= 1001, amount=    1.00
2018-04-25 11:33:19,307 INFO  [DubboServerHandler-192.168.99.1:20882-thread-3] org.bytesoft.bytejta.TransactionImpl - [0a002700000400000162fadb19ba00014f694991] delist: xares= xa-res-archive[descriptor: local-xa-resource[dataSource]], branch= 0a002700000400000162fadca7270002f769c444, flags= 67108864
2018-04-25 11:33:19,310 INFO  [DubboServerHandler-192.168.99.1:20882-thread-3] org.bytesoft.bytejta.TransactionImpl - [0a002700000400000162fadb19ba00014f694991] prepare-transaction start
2018-04-25 11:33:19,310 INFO  [DubboServerHandler-192.168.99.1:20882-thread-3] org.bytesoft.bytejta.resource.XATerminatorOptd - [0a002700000400000162fadb19ba00014f694991] prepare: xares= xa-res-archive[descriptor: local-xa-resource[dataSource]], branch= 0a002700000400000162fadca7270002f769c444, vote= 0
2018-04-25 11:33:19,310 INFO  [DubboServerHandler-192.168.99.1:20882-thread-3] org.bytesoft.bytejta.TransactionImpl - [0a002700000400000162fadb19ba00014f694991] prepare-transaction complete successfully
2018-04-25 11:33:19,310 INFO  [DubboServerHandler-192.168.99.1:20882-thread-3] org.bytesoft.bytejta.TransactionImpl - [0a002700000400000162fadb19ba00014f694991] commit-transaction start
2018-04-25 11:33:19,317 INFO  [DubboServerHandler-192.168.99.1:20882-thread-3] org.bytesoft.bytejta.resource.XATerminatorOptd - [0a002700000400000162fadb19ba00014f694991] commit: xares= xa-res-archive[descriptor: local-xa-resource[dataSource]], branch= 0a002700000400000162fadca7270002f769c444, opc= false
2018-04-25 11:33:19,317 INFO  [DubboServerHandler-192.168.99.1:20882-thread-3] org.bytesoft.bytetcc.CompensableTransactionImpl - 0a002700000400000162fad4af780001d1fd8acc| confirm: identifier= 0a002700000400000162fad4af780001d1fd8acc, resourceKey= dataSource, resourceXid= 1207-0a002700000400000162fadb19ba00014f694991-0a002700000400000162fadca7270002f769c444.
2018-04-25 11:33:19,317 INFO  [DubboServerHandler-192.168.99.1:20882-thread-3] org.bytesoft.bytejta.TransactionImpl - [0a002700000400000162fadb19ba00014f694991] commit-transaction complete successfully
2018-04-25 11:33:19,317 INFO  [DubboServerHandler-192.168.99.1:20882-thread-3] org.bytesoft.bytetcc.CompensableTransactionImpl - 0a002700000400000162fad4af780001d1fd8acc| compensable transaction committed!
2018-04-25 11:33:19,318 INFO  [DubboServerHandler-192.168.99.1:20882-thread-3] org.bytesoft.bytetcc.CompensableTransactionImpl - 0a002700000400000162fad4af780001d1fd8acc| forget transaction.
2018-04-25 11:33:19,318 INFO  [pool-1-thread-1] org.bytesoft.bytetcc.CompensableTransactionImpl - 0a002700000400000162fad4af780001d1fd8acc| forget transaction.
```

Debug 看到 CompensableInvocation 的 method 是 decreaseAmount，但是下一步执行就不对
```
increaseAmount:22, AccountServiceConfirm (com.bytesvc.service.confirm)
invoke:-1, AccountServiceConfirm$$FastClassBySpringCGLIB$$bc4514ce (com.bytesvc.service.confirm)
invoke:204, MethodProxy (org.springframework.cglib.proxy)
invokeJoinpoint:711, CglibAopProxy$CglibMethodInvocation (org.springframework.aop.framework)
proceed:157, ReflectiveMethodInvocation (org.springframework.aop.framework)
proceedWithInvocation:98, TransactionInterceptor$1 (org.springframework.transaction.interceptor)
invokeWithinTransaction:262, TransactionAspectSupport (org.springframework.transaction.interceptor)
invoke:95, TransactionInterceptor (org.springframework.transaction.interceptor)
proceed:179, ReflectiveMethodInvocation (org.springframework.aop.framework)
intercept:644, CglibAopProxy$DynamicAdvisedInterceptor (org.springframework.aop.framework)
increaseAmount:-1, AccountServiceConfirm$$EnhancerBySpringCGLIB$$f9d47d80 (com.bytesvc.service.confirm)
invoke0:-1, NativeMethodAccessorImpl (sun.reflect)
invoke:57, NativeMethodAccessorImpl (sun.reflect)
invoke:43, DelegatingMethodAccessorImpl (sun.reflect)
invoke:606, Method (java.lang.reflect)
confirmComplicated:89, SpringContainerContextImpl (org.bytesoft.bytetcc.supports.spring)
confirm:46, SpringContainerContextImpl (org.bytesoft.bytetcc.supports.spring)
fireNativeParticipantConfirm:256, CompensableTransactionImpl (org.bytesoft.bytetcc)
fireCommit:156, CompensableTransactionImpl (org.bytesoft.bytetcc)
participantCommit:123, CompensableTransactionImpl (org.bytesoft.bytetcc)
invokeCommit:206, CompensableCoordinator (org.bytesoft.bytetcc)
commit:160, CompensableCoordinator (org.bytesoft.bytetcc)
commit:56, TransactionCoordinator (org.bytesoft.bytetcc)
invokeMethod:-1, Wrapper2 (com.alibaba.dubbo.common.bytecode)
doInvoke:46, JavassistProxyFactory$1 (com.alibaba.dubbo.rpc.proxy.javassist)
invoke:72, AbstractProxyInvoker (com.alibaba.dubbo.rpc.proxy)
invoke:53, InvokerWrapper (com.alibaba.dubbo.rpc.protocol)
wrapResultForProvider:285, CompensableServiceFilter (org.bytesoft.bytetcc.supports.dubbo.spi)
providerInvokeForTCC:178, CompensableServiceFilter (org.bytesoft.bytetcc.supports.dubbo.spi)
providerInvoke:86, CompensableServiceFilter (org.bytesoft.bytetcc.supports.dubbo.spi)
invoke:71, CompensableServiceFilter (org.bytesoft.bytetcc.supports.dubbo.spi)
invoke:91, ProtocolFilterWrapper$1 (com.alibaba.dubbo.rpc.protocol)
invoke:64, ExceptionFilter (com.alibaba.dubbo.rpc.filter)
invoke:91, ProtocolFilterWrapper$1 (com.alibaba.dubbo.rpc.protocol)
invoke:42, TimeoutFilter (com.alibaba.dubbo.rpc.filter)
invoke:91, ProtocolFilterWrapper$1 (com.alibaba.dubbo.rpc.protocol)
invoke:75, MonitorFilter (com.alibaba.dubbo.monitor.support)
invoke:91, ProtocolFilterWrapper$1 (com.alibaba.dubbo.rpc.protocol)
invoke:78, TraceFilter (com.alibaba.dubbo.rpc.protocol.dubbo.filter)
invoke:91, ProtocolFilterWrapper$1 (com.alibaba.dubbo.rpc.protocol)
invoke:60, ContextFilter (com.alibaba.dubbo.rpc.filter)
invoke:91, ProtocolFilterWrapper$1 (com.alibaba.dubbo.rpc.protocol)
invoke:112, GenericFilter (com.alibaba.dubbo.rpc.filter)
invoke:91, ProtocolFilterWrapper$1 (com.alibaba.dubbo.rpc.protocol)
invoke:38, ClassLoaderFilter (com.alibaba.dubbo.rpc.filter)
invoke:91, ProtocolFilterWrapper$1 (com.alibaba.dubbo.rpc.protocol)
invoke:38, EchoFilter (com.alibaba.dubbo.rpc.filter)
invoke:91, ProtocolFilterWrapper$1 (com.alibaba.dubbo.rpc.protocol)
reply:108, DubboProtocol$1 (com.alibaba.dubbo.rpc.protocol.dubbo)
handleRequest:84, HeaderExchangeHandler (com.alibaba.dubbo.remoting.exchange.support.header)
received:170, HeaderExchangeHandler (com.alibaba.dubbo.remoting.exchange.support.header)
received:52, DecodeHandler (com.alibaba.dubbo.remoting.transport)
run:82, ChannelEventRunnable (com.alibaba.dubbo.remoting.transport.dispatcher)
runWorker:1145, ThreadPoolExecutor (java.util.concurrent)
run:615, ThreadPoolExecutor$Worker (java.util.concurrent)
run:745, Thread (java.lang)
```

**Comment by wujun8** [comment]
出现问题时，发现 invoke 前的 Method.slot = 0, 正常情况下 decreaseAmount slot=1, 见截图
![image](https://user-images.githubusercontent.com/7053898/39245174-86156534-48c5-11e8-96f2-c194eee9635d.png)

所以，这里应该是反序列化时，slot 没有值然后默认初始化为 0

**Comment by liuyangming** [comment]
好的，感谢反馈，我查查看。

**Comment by liuyangming** [comment]
该问题由kryo对CompensableInvocationImpl/CompensableInvocationInfo的序列化/反序列化不正确导致，已在0.4.13版本中修复，请使用最新版本。

**Comment by wujun8** [comment]
```java.lang.reflect.Method``` 这个对象不能序列化，其中 slot 值是随机顺序的，每次 Runtime 可能会变化，虽然其它信息正确，但是 JDK 最终 invoke 还是依赖于 slot ，所以还是自己记录类及方法信息可靠

**Comment by liuyangming** [comment]
CompensableInvocationImpl/CompensableInvocationInfo中有writeReplace/readResolve对java.lang.reflect.Method进行处理，不过kryo没执行；而且Method类没实现Serializable居然也不提示错误，感觉不太符合java序列化的规范。

**Comment by wujun8** [comment]
writeReplace/readResolve 不被调用的原因是，kryo 需要显示启用该特性，且必须在 Java8 环境，对于 closures 的对象类型才会使用 ClosureSerializer 调用 writeReplace/readResolve （这个在 kryo 也只有 ClosureSerializer 会调用）
不然，对于自定义 Class 就是 FieldSerializer 序列化所有非 transient 字段，会忽略 Java Serializable 的约束（writeReplace/readResolve）

从这点来看，kryo 其实没做错什么，它尽力做到全部序列化了（尽管你不实现 Serializable ），而且反序列化时也没有错误，只是 Java 反射机制的 method.slot 是不可靠的随机值导致了上述问题
